# Pytorch 深度学习 和 图神经网络

In [1]:
import torch
print(torch.cuda.is_available())

True


## 第四章 快速上手 Pytorch

In [2]:
# torch.tensor()函数，不常用
import torch 
import numpy as np
a = torch.tensor(5)
print(a)

a = torch.tensor(np.asarray([4]))
print(a)

tensor(5)
tensor([4], dtype=torch.int32)


In [8]:
# torch.Tensor()函数
import torch
import numpy as np

a = torch.Tensor(2)
print(a)

b = torch.Tensor(1, 2, 3) # 默认初始化为 0 
print(b)

c = torch.Tensor([1, 2])
print(c)

print(torch.numel(b)) # 张量中元素的个数

tensor([0.0000e+00, 4.1992e-05])
tensor([[[-4.7392e-38,  1.2556e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
tensor([1., 2.])
6


In [11]:
a = torch.ones(2, 2)
b = torch.zeros(2, 3)
c = torch.randn(3, 3)
print(a)
print(b)
print(c)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.6460, -0.9464, -0.1764],
        [-1.5066,  0.8905, -0.5115],
        [ 0.5933, -0.7074,  0.5170]])


In [14]:
# CPU 与 GPU
import torch

a = torch.Tensor([4]) 
b = a.cuda()
print(b)

a = torch.tensor([2], device = "cuda") # 注意必须是小写 tensor
print(a)

tensor([4.], device='cuda:0')
tensor([2], device='cuda:0')


In [19]:
# 随机值
import torch

torch.initial_seed()
torch.manual_seed(2) # 设置种子
torch.initial_seed()

print(torch.randn(2, 3))

tensor([[ 0.3923, -0.2236, -0.3195],
        [-1.2050,  1.0445, -0.6332]])


In [22]:
# torch.reshape()
import torch

a = torch.Tensor([[1, 2], [3, 4]])
print(torch.reshape(a, (1, -1)))
print(torch.reshape(a, (4, 1)))

tensor([[1., 2., 3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [25]:
# 张量的矩阵转置
import torch

b = torch.Tensor(1, 3)
print(b)
print(torch.t(b))
torch.transpose(b, dim0 = 1, dim1 = 0)
print(b)

tensor([[0.0000e+00, 2.2500e+00, 1.4013e-45]])
tensor([[0.0000e+00],
        [2.2500e+00],
        [1.4013e-45]])
tensor([[0.0000e+00, 2.2500e+00, 1.4013e-45]])


In [28]:
import torch

a = torch.Tensor([[1, 2], [3, 4]])
b = torch.Tensor([[5, 6], [7, 8]])
print(torch.cat([a, b], dim=0))
print(torch.cat([a, b], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [30]:
# Variable 类型 与 自动微分模块
import torch
from torch.autograd import Variable

a = torch.Tensor([4])
print(Variable(a))

print(Variable(a, requires_grad=True))



tensor([4.])
tensor([4.], requires_grad=True)


In [38]:
# torch.no_grad() 介绍
import torch
from torch.autograd import Variable

x = torch.ones(2, 2, requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)

with torch.no_grad():
    with torch.enable_grad():
        y = x * 2

print(y.requires_grad)

False
True


In [43]:
# set_grad_enabled()
import torch
from torch.autograd import Variable

x = torch.ones(2, 2, requires_grad=True)
torch.set_grad_enabled(False)
y = x * 2
print(x.requires_grad)
print(y.requires_grad)

torch.set_grad_enabled(True)
print(y.requires_grad)
y = x * 2
print(y.requires_grad)

True
False
False
True


In [45]:
# Variable对象的grad_fn属性
import torch
from torch.autograd import Variable

x = Variable(torch.ones(2, 2), requires_grad=True)
print(x, x.grad_fn)

m = x + 2
print(m.grad_fn)
print(m.grad_fn(x)) # 求导成功

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None
(tensor([[1., 1.],
        [1., 1.]], requires_grad=True), None)


In [48]:
# Variable对象 的 is_leaf 属性
import torch
from torch.autograd import Variable

x = Variable(torch.ones(2, 2), requires_grad=True)
print(x.is_leaf)
m = x + 2
print(m.is_leaf)
print(m.requires_grad)

True
False
True


In [49]:
# backward() 自动求导
import torch
from torch.autograd import Variable

x = Variable(torch.ones(2, 2), requires_grad=True)
m = x + 2
f = m.mean() # 得到一个标量
f.backward()
print(f, x.grad)

tensor(3., grad_fn=<MeanBackward0>) tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [32]:
# 激活函数
import torch

input = torch.autograd.Variable(torch.randn(2))
print(input)
print(nn.Sigmoid()(input))
print(nn.LogSigmoid()(input))

print(torch.tanh(input, out=None))

print(torch.relu(input))
# print(torch.nn.relu(input, inplace=False))

tensor([-0.8250, -0.2646])
tensor([0.3047, 0.4342])
tensor([-1.1884, -0.8342])
tensor([-0.6778, -0.2586])
tensor([0., 0.])


In [41]:
## nn模块中的损失函数
import torch

pre = torch.Tensor([1])
label = torch.Tensor([-1])

loss1 = torch.nn.L1Loss()(pre, label)
print(loss1)

loss2 = torch.nn.MSELoss()(pre, label)
print(loss2)

loss3 = torch.nn.CrossEntropyLoss()(pre, label)
print(loss3)

tensor(2.)
tensor(4.)
tensor(-0.)


In [43]:
# 优化器模块
import torch

optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)